name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to GitHub Packages
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
        registry-url: 'https://npm.pkg.github.com'
        scope: '@timemachinemedia'
    - run: npm install
    - run: npm run build -- --prod
    - uses: MontyD/package-json-updated-action@1.0.1
      id: check_version
      with:
        path: projects/reviews/package.json
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - run: |
        cd dist/reviews
        npm publish
      if: steps.check_version.outputs.has-updated
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
